### ISSUE TITLE
Micro::Case#then(:method_name)

### ISSUE THREAD

**Issue by tiagofsilva** [serradura/u-case#118]
Hi folks! Just finished seeing the second ada.rb meeting and had the opportunity of seeing u-case at work. I've been checking it out once in a while but now I decided to give it a try. So congrats, first of all. It looks really pretty! :clap: 
So I was wondering if there is a way I can avoid using `Micro::Case#then(method(:method_name))`. It is a bit of metaprogramming in an undesired way (even though it is a simple one). Even using `apply` as an alias still is not ideal, I think. Because the user needs to know about the existence of this #apply method just to pass what he wanted in the end, which is, just a symbol or string identifying the method he wants to call next. 
Ideally we could have something like:

```
def call!
  normalize_params
    .then(:sanitize)
    .then(:validate)
    .then(Persist)
end
```
`then` would be responsible for directing to the next use case independent of what you pass. This would make the method more robust in what it accepts (https://www.justinweiss.com/articles/simplify-your-ruby-code-with-the-robustness-principle/) and would have a common way of chaining use cases. 
Of course, I'd be willing to contribute to that. But first, what do you guys think about it?

**Comment by serradura** [comment]
@tiagofsilva I really appreciate knowing that you are enjoying this gem and thanks for watching the ada.rb meetup.

The idea of using method is to make an explicit declaration that you are using something of the current `u-case`, so there is no magic, we are only using a native Ruby feature.

I understand your point and I think that other users could prefer your suggestion. So, I'm opened to receive a pull request with this contribution. And please, reach in contact if you need some help to make this implementation.
